binance:
  spot:
    requests_per_min: 1200
    notes: "Limites par endpoint/weight; backoff sur 429/418"
  futures:
    requests_per_min: 2400
    orders_per_min: 1200
    notes: "2400 rpm/IP typique; ajuster selon endpoints"

telegram:
  per_chat_rps: 1
  per_group_rpm: 20
  global_rps: 30

newsapi:
  requests_per_day: 100
  burst_rps: 1

fred:
  requests_per_min: 120

yahoo_provider:
  name: "provisional"
  requests_per_min: 60
  requests_per_day: 3000
  notes: "Remplacer ces valeurs dès provider choisi."

gnews:
  requests_per_day: 25000
  burst_rps: 8

newsdata:
  requests_per_15min: 30
  requests_per_min: 2
