version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file_rotating:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: logs/system.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf-8
loggers:
  sniper:
    level: INFO
    handlers: [console, file_rotating]
    propagate: false
root:
  level: WARNING
  handlers: [console]
